project:
  type: website
  output-dir: docs
  preview:
    port: 7209
    browser: true

# this stops code from being executed on GitHub Actions when deploying. I want some code running right now though
# execute:
#   freeze: auto

website:
  title: "The Azimuth Project"
  favicon: /static/images/favicon.ico
  # site-url: https://www.kyleGrealis.com/

  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: About
        href: about/index.qmd
      - text: R Packages
        href: r-packages/index.qmd
      - text: Apps
        href: apps/index.qmd
      # - text: NASCAR
      #   href: nascar/dashboard.qmd
      - text: Blog
        href: blog/index.qmd
      - text: UM Team
        href: https://kylegrealis.github.io/feaster-balise-lab/
      - icon: github
        href: https://github.com/kyleGrealis/
        target: _blank

  page-footer:
    background: "#4c566a"
    center: This website is built with [Quarto](https://quarto.org/docs/website) &copy;2025

format:
  html:
    theme: [styles.scss]
    toc: true
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap

