project:
  type: website
  output-dir: docs
  preview:
    port: 7209
    browser: true

# this stops code from being executed on GitHub Actions when deploying. I want some code running right now though
# execute:
#   freeze: auto

website:
  title: "kyleGrealis.com"
  favicon: /static/images/favicon.ico
  site-url: https://www.kyleGrealis.com/about/

  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: R Packages
        href: r-packages/index.qmd
      - text: Shiny Apps
        href: apps/index.qmd
      - text: Presentations
        href: presentations/index.qmd
      - text: Publications
        href: https://scholar.google.com/citations?hl=en&user=sdB7YAkAAAAJ
        target: _blank
      - icon: github
        href: https://github.com/kyleGrealis/
        target: _blank

  page-footer:
    background: "#4c566a"
    center: This website is built with [Quarto](https://quarto.org/docs/website) &copy;2026

format:
  html:
    theme: [styles.scss]
    toc: true
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap

