project:
  type: website
  output-dir: docs

website:
  title: "kyleGrealis.github.io"
  favicon: /static/images/favicon.ico
  page-footer:
    background: dark
    center: This website is built with [Quarto](https://quarto.org/docs/website) &copy;2024
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: posts.qmd
        text: Blog
      - icon: github
        href: https://github.com/kyleGrealis/
        target: _blank

format:
  html:
    theme: sandstone
    css: styles.css
    highlight-style: espresso
    toc: true
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap

