project:
  type: website
  output-dir: docs

website:
  title: "kyleGrealis.github.io"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: how-to-scrape-google-scholar.qmd
        text: Webscraping

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



