project:
  type: website
  output-dir: docs

# this stops code from being executed on GitHub Actions when deploying. I want some code running right now though
# execute:
#   freeze: auto

website:
  title: "kyleGrealis.github.io"
  favicon: /static/images/favicon.ico

  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: cran/index.qmd
        text: R Packages
      - href: apps/index.qmd
        text: Apps
      - href: blog/index.qmd
        text: Blog
      - href: https://kylegrealis.github.io/feaster-balise-lab/
        text: Team
      - icon: github
        href: https://github.com/kyleGrealis/
        target: _blank

  page-footer:
    background: "#4c566a"
    center: This website is built with [Quarto](https://quarto.org/docs/website) &copy;2025

format:
  html:
    theme: [styles.scss]
    toc: true
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap

