project:
  type: website
  output-dir: docs

website:
  title: "kyleGrealis.github.io"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      # - href: how-to-scrape-google-scholar.qmd
      #   text: Webscraping

format:
  html:
    theme: sandstone
    css: styles.css
    highlight-style: espresso
    toc: true
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap

